### ISSUE TITLE
Base 64 issue

### ISSUE THREAD

**Issue by AayushGoyal22** [Pymmdrza/Pyromid#1]
ERROR: Could not find a version that satisfies the requirement base64 (from versions: none)
ERROR: No matching distribution found for base64

i am not sure i tried many things but didnt work for me please kindly help me.

**Comment by Pymmdrza** [comment]
> ERROR: Could not find a version that satisfies the requirement base64 (from versions: none) ERROR: No matching distribution found for base64
> 
> i am not sure i tried many things but didnt work for me please kindly help me.

no need to install `base64` . in default package python.
