### ISSUE TITLE
No results!

### ISSUE THREAD

**Issue by nscpro** [Pymmdrza/Pyromid#3]
This working for me over week and no results :(

**Comment by Pymmdrza** [comment]
> This working for me over week and no results :(

**i very very busy sorry .**

**Comment by OmartGhani** [comment]
Yes your priorities just a money oriented client. this why we not get a clear answers. when you thinking you are real good programmer for newbie like me, what's u share sintake error and error fake python script

**Comment by Pymmdrza** [comment]
> Yes your priorities just a money oriented client. this why we not get a clear answers. when you thinking you are real good programmer for newbie like me, what's u share sintake error and error fake python script

_I wish you success._
