### ISSUE TITLE
SyntaxError Windows

### ISSUE THREAD

**Issue by BTGMiningUSA** [Pymmdrza/Pyromid#4]
File "pyromid_V2.py", line 10
    key += f"{k}"
                     ^
SyntaxError: invalid syntax

On Original version
File "pyromid.py", line 2
SyntaxError: Non-ASCII character '\xe2' in file pyromid.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by OmartGhani** [comment]
Yes it's fake py script
I think just a prank maybe for this program

**Comment by Pymmdrza** [comment]
> File "pyromid_V2.py", line 10 key += f"{k}" ^ SyntaxError: invalid syntax
> 
> On Original version File "pyromid.py", line 2 SyntaxError: Non-ASCII character '\xe2' in file pyromid.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

---

### install & use Pyromid v2:

#### windows with `pip`:
```bash
pip install cryptofuzz
pip install colorthon
```
#### Linux & Mac with `pip3`:


```bash
sudo apt-get update&&sudo apt-get upgrade -y
pip3 install cryptofuzz
pip3 install colorthon
```


running Online On Replit : [Run Now](https://replit.com/@MrPyMmdrza/Pyromid-v2)





### screen :  

![](https://raw.githubusercontent.com/Pymmdrza/Pyromid/media/media/pyromid2.gif)
