### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by SayedXv** [Pymmdrza/Pyromid#6]
Can i run this script on termux with linux?

**Comment by Pymmdrza** [comment]
I did not check. If you have Python in it, you can run it

[Pyromid_V2.py](https://github.com/Pymmdrza/Pyromid/blob/mainx/Pyromid_V2.py)

```shell
# windows 
pip install cryptofuzz
pip install colorthon
# linux & mac
pip3 install cryptofuzz
pip3 install colorthon
```
