### ISSUE TITLE
Pyromid V3

### ISSUE THREAD

**Issue by SayedXv** [Pymmdrza/Pyromid#8]
When will you release Pyromid V3?

**Comment by saeedtour** [comment]
سلام
نسخه 3 رو کی قرار میدین؟

**Comment by vaiosx** [comment]
there no any connection to the servers
В коде нет ничего связанного с подключением для брутфорса, просто бесполезная генерация.

**Comment by Pymmdrza** [comment]
> When will you release Pyromid V3?

**very soon**
